import { promises as fs } from "fs"
import path from "path"

import { UPLOAD_DIR } from "@/lib/storage"

// Uploads live outside public/ (next start only serves public files that
// existed at build time), so they're streamed from UPLOAD_DIR here.
const TYPES: Record<string, string> = {
  png: "image/png",
  jpg: "image/jpeg",
  gif: "image/gif",
  webp: "image/webp",
  avif: "image/avif",
}

// Names are generated by /api/uploads: <uuid>.<ext>. Anything else is refused,
// which also rules out path traversal.
const NAME_RE = /^[0-9a-f-]{36}\.(png|jpg|gif|webp|avif)$/i

export async function GET(_request: Request, ctx: RouteContext<"/uploads/[file]">) {
  const { file } = await ctx.params
  const match = file.match(NAME_RE)
  if (!match) return new Response("Not found", { status: 404 })

  try {
    const data = await fs.readFile(path.join(UPLOAD_DIR, file))
    return new Response(data, {
      headers: {
        "Content-Type": TYPES[match[1].toLowerCase()],
        // Names are unique per upload, so the file never changes.
        "Cache-Control": "public, max-age=31536000, immutable",
      },
    })
  } catch {
    return new Response("Not found", { status: 404 })
  }
}
